spring.application.name=AyurSutraBackend

# Disable MySQL for Render deploy
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Server Port (Render compatible)
server.port=${PORT:8080}

# JWT Secret
jwt.secret=ayursutraSuperSecretKeyForJwtAuthenticationAlgorithm2026!@#
jwt.expirationMs=86400000

# Gemini API
gemini.api.key=AIzaSyAsEBMX8U7XTOjii17QeFwMrLZ7KgEyGHk
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent

# Twilio
twilio.account.sid=AC3d49f97fd5fa3bdaf28450596827b1a0
twilio.auth.token=5e6124281243f945a9481608d540fd03
twilio.phone.number=+13083205261